version: 2.0

references:
  
  container_config: &container_config
    docker:
      - image: singlaive/texlive_curl:0.1
    working_directory: /root/build
    
general:
  branches:
    only:
      - master

jobs:
  build_deploy:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: build
          command: |
            xelatex resume.tex
            mkdir output
            cp resume.pdf output/
            mkdir /tmp/artifacts
            cp resume.pdf /tmp/artifacts/resume_$CIRCLE_BUILD_NUM.pdf

      - persist_to_workspace:
          root: output
          paths:
            - resume.pdf

      - store_artifacts:
          path: /tmp/artifacts

      - deploy:
          name: Deploy Master to Dropbox
          command: |
            ./dropbox_uploader.sh -f .dropbox_uploader upload /tmp/artifacts/resume_$CIRCLE_BUILD_NUM.pdf resume.pdfs       

workflows:
  version: 2

  default_workflow:
    jobs:
      - build_deploy
